version: '3.5'
 
services:
  postgres:
    container_name: postgres_container_dataproject
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
   
  pgadmin:
    container_name: pgadmin_container_dataproject
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  python-script:
    build: .
    container_name: dataproject_app
    depends_on:
      - postgres
    networks:
      - postgres 
    ports:
      - "8501:8501"   

 
networks:
  postgres:
    driver: bridge
 
volumes:
    postgres:
    pgadmin: